# Generated by Django 5.1 on 2024-08-31 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование задачи",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        help_text="Введите срок исполнения", verbose_name="Deadline"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("create", "create"),
                            ("start", "start"),
                            ("finish", "finish"),
                        ],
                        default="create",
                        help_text="Введите статус",
                        verbose_name="Status",
                    ),
                ),
                (
                    "father_task",
                    models.CharField(
                        choices=[("father", "father"), ("other", "other")],
                        default="father",
                        help_text="Это главная задача",
                        verbose_name="Father task",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите исполнителя",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                        verbose_name="Executor",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите родительскую задачу",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task_tracker.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
