# Generated by Django 5.1 on 2024-08-28 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_tracker", "0004_alter_task_parent_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                default="admin",
                help_text="Введите родительскую задачу",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="task_tracker.task",
            ),
        ),
    ]
